/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;
import java.awt.Toolkit;
import model.*;

/**
 *
 * @author joaot
 */
public class window extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(window.class.getName());
    /**
     * Creates new form window
     */
    
    private String title_print;
    
    public window() {
        title_print = "";
        initComponents();
    }
    
    public void Enter(int init, String title, int r, int t, int w, int h){
        
        if(r < 0) r = 0;
        if(t < 0) t = 0;
        
        if(r >= 100) r = 100;
        if(t >= 100) t = 100;
        
        if(w < 600) w = 600;
        if(h < 300) h = 300;
        
        Exec(init,r,t,w,h);
        
    }//Enter(String title, int r, int l, int w, int h)
    
    public void Enter(int init, int r, int t){
        
        if(r < 0) r = 0;
        if(t < 0) t = 0;
        
        if(r >= 100) r = 100;
        if(t >= 300) t = 300;
        
        Exec(init,r,t,600,300);
        
    }//public void Enter(int init, String title)
    
    private void Exec(int init, int r, int t, int w, int h){
        
        setVisible(true);
        setResizable(init > 0);
        
        var tool = Toolkit.getDefaultToolkit().getScreenSize();
        
        var width = tool.width - r;
        var height = tool.height - t;
        
        if(width > 120) width -= 100;
        if(height > 120) height -= 100;
        
        if(w > width) w = width;
        if(h > height) h = height;
        
        setBounds(r, t, w, h);
        
        boolean tem[] = new boolean[2];
        
        for(int exe = 0; exe < tem.length; exe++){
            
            if(init >= 0 && init < tem.length){
                
                tem[exe] = exe == init;
                
            } else {//if(init >= 0 && init < tem.length)
                
                tem[exe] = exe == 0;
                
            }//if(init >= 0 && init < tem.length)
            
        }//for(int exe = 0; exe < tem.length; exe++)
        
        Command(tem[0]);
        
        Title();
        
    }//Enter(String title, int r, int l, int w, int h)
    
    private void Title(){
        
        var title = new Data().DataAbreviada(true);
        title += " - Bo";
        title += Hora.Good("m Dia", "a Tarde", "a Noite");
        title += "!";
        
        setTitle(title);
        
        var tem = Reg.Tab(title, new Hora(false).TimerGood(true),40);
        
        if(!title_print.equalsIgnoreCase(tem)){
            System.out.println(Reg.Tab(title, new Hora(true).TimerGood(true),40));
        }
        
        title_print = tem;
        
    }//Title()
    
    private void Command(boolean execute){
        
        initial.setVisible(execute);
        
        if(execute){
            
            final var node1 = Reg.modify.DataCompleta("#");
            final var node2 = node1.indexOf("#");
            final var node = node1.substring(0, node2);
            
            ide.setFont(new java.awt.Font("Segoe UI Black", 0, 36));
            ide.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
            
            categories.setFont(new java.awt.Font("Tahoma", 0, 22));
            categories.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
            
            choose.setFont(new java.awt.Font("Tahoma", 0, 22));
            choose.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
            
            modify1.setFont(new java.awt.Font("Times New Roman", 3, 22));
            modify1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
            
            modify2.setFont(new java.awt.Font("Times New Roman", 2, 22));
            modify2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
            
            modify3.setFont(new java.awt.Font("Times New Roman", 2, 22));
            modify3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
            
            ide.setText(Reg.ide);
            categories.setText(Reg.categories);
            choose.setText(Reg.choose);
            modify1.setText("Última modificação:");
            modify2.setText(node);
            modify3.setText(Reg.modify.DataCompleta(false));
            
        }//if(execute)
        
    }//Command(boolean execute)

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        initial = new javax.swing.JPanel();
        ide = new javax.swing.JLabel();
        categories = new javax.swing.JLabel();
        choose = new javax.swing.JLabel();
        modify1 = new javax.swing.JLabel();
        modify2 = new javax.swing.JLabel();
        modify3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        initial.setAlignmentX(0.0F);
        initial.setAlignmentY(0.0F);
        initial.setMaximumSize(new java.awt.Dimension(600, 600));
        initial.setMinimumSize(new java.awt.Dimension(600, 600));
        initial.setPreferredSize(new java.awt.Dimension(600, 300));
        initial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                initialMouseReleased(evt);
            }
        });
        initial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                initialKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                initialKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                initialKeyTyped(evt);
            }
        });

        ide.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        ide.setText("Java NetBeans IDE 27");

        categories.setText("Java width Ant");

        choose.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        choose.setText("Java Application");

        modify1.setText("Última modificação");

        modify2.setText("Dia da SEMANA");

        modify3.setText("Dia do MÊS");

        javax.swing.GroupLayout initialLayout = new javax.swing.GroupLayout(initial);
        initial.setLayout(initialLayout);
        initialLayout.setHorizontalGroup(
            initialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, initialLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(initialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(modify1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(initialLayout.createSequentialGroup()
                        .addComponent(modify2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(modify3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(ide, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, initialLayout.createSequentialGroup()
                        .addComponent(categories, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(choose, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40))
        );
        initialLayout.setVerticalGroup(
            initialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(initialLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ide, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(initialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(choose, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(categories, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(modify1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(initialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(modify2, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(modify3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(initial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(initial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initialKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_initialKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_initialKeyReleased

    private void initialKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_initialKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_initialKeyPressed

    private void initialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_initialKeyTyped
        System.out.println(evt.getKeyChar());
    }//GEN-LAST:event_initialKeyTyped

    private void initialMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_initialMouseReleased
        Title();
    }//GEN-LAST:event_initialMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new window().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel categories;
    private javax.swing.JLabel choose;
    private javax.swing.JLabel ide;
    private javax.swing.JPanel initial;
    private javax.swing.JLabel modify1;
    private javax.swing.JLabel modify2;
    private javax.swing.JLabel modify3;
    // End of variables declaration//GEN-END:variables
}
