/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;
import java.awt.Toolkit;
import model.Reg;

/**
 *
 * @author josue
 */
public class window extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(window.class.getName());
    /**
     * Creates new form window
     */
    
    private String tem_0;
    
    public window() {
        
        initComponents();
        setVisible(true);
        setResizable(true);
        
        this.tem_0 = "";
        
    }//window()
    
    public void Enter(
        boolean print,
        int init,
        String title,
        int r,
        int t,
        int w,
        int h
    )
    {
        
        if(r < 0) r = 0;
        if(t < 0) t = 0;
        
        if(r >= 100) r = 100;
        if(t >= 100) t = 100;
        
        if(w < 700) w = 700;
        if(h < 400) h = 400;
        
        Exec(init,r,t,w,h);
        
    }//Enter(String title, int r, int l, int w, int h)
    
    public void Enter(int init, int r, int t){
        
        if(r < 0) r = 0;
        if(t < 0) t = 0;
        
        Exec(init,r,t,600,600);
        
    }//public void Enter(int init, String title)
    
    public void Enter(int init){
        
        Exec(init,50,50,600,600);
        
    }//public void Enter(int init, String title)
    
    private void Exec(int init, int r, int t, int w, int h){
        
        var tool = Toolkit.getDefaultToolkit().getScreenSize();
        
        var rw = tool.width - w - 10;
        var th = tool.height - h - 50;
        
        if(rw < 0) rw = 0;
        if(th < 0) th = 0;
        
        if(r < 0) r = 0;
        if(t < 0) t = 0;
        
        if(r > rw) r = rw;
        if(t > th) t = th;
        
        var width = tool.width - r;
        var height = tool.height - t;
        
        if(w > width) w = width;
        if(h > height) h = height;
        
        setBounds(r, t, w, h);
        
        Tem(init);
        
    }//Enter(String title, int r, int l, int w, int h)
    
    public void Title(String title){
        
        setTitle(title);
        
    }
    
    public void Tem_0(String text){
        
        var txt = "";
        
        for(String t : text.split("\n")){
            
            txt += "\n";
            txt += " ".repeat(5);
            txt += t;
            
        }//for(String t : text.split("\n"))
        
        this.tem_0 = txt;
        
        Tem(0);
        
    }//Tem_0(String text)
    
    public void Tem(int init){
        
        boolean tem[] = new boolean[2];
        
        for(int exe = 0; exe < tem.length; exe++){
            
            if(init >= 0 && init < tem.length){
                
                tem[exe] = exe == init;
                
            } else {//if(init >= 0 && init < tem.length)
                
                tem[exe] = exe == 0;
                
            }//if(init >= 0 && init < tem.length)
            
        }//for(int exe = 0; exe < tem.length; exe++)
        
        Command(tem[0]);
        
    }//Tem(int init)
    
    private void Command(boolean execute){
        
        initial.setVisible(execute);
        
        if(execute){
            
            ide.setFont(new java.awt.Font("Segoe UI Black", 0, 36));
            ide.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            ide.setText(Reg.ide);
            
            categories.setFont(new java.awt.Font("Tahoma", 0, 32));
            categories.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
            categories.setText(" ".repeat(2) + Reg.categories);
            
            choose.setFont(new java.awt.Font("Tahoma", 0, 32));
            choose.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
            choose.setText(Reg.choose + " ".repeat(2));
            
            cont.setEditable(false);
            cont.setFocusable(false);
            cont.setFont(new java.awt.Font("Times New Roman", 0, 12));
            cont.setText(this.tem_0);
            
        }//if(execute)
        
    }//Command(boolean execute)

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        initial = new javax.swing.JPanel();
        ide = new javax.swing.JLabel();
        categories = new javax.swing.JLabel();
        choose = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cont = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        initial.setAlignmentX(0.0F);
        initial.setAlignmentY(0.0F);
        initial.setDoubleBuffered(false);
        initial.setEnabled(false);
        initial.setMaximumSize(new java.awt.Dimension(600, 600));
        initial.setMinimumSize(new java.awt.Dimension(600, 600));
        initial.setPreferredSize(new java.awt.Dimension(600, 600));
        initial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                initialMouseReleased(evt);
            }
        });
        initial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                initialKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                initialKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                initialKeyTyped(evt);
            }
        });

        ide.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        ide.setText("Java NetBeans IDE 27");
        ide.setPreferredSize(new java.awt.Dimension(186, 500));

        categories.setText("Java width Ant");
        categories.setPreferredSize(new java.awt.Dimension(90, 200));

        choose.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        choose.setText("Java Application");
        choose.setPreferredSize(new java.awt.Dimension(90, 200));

        cont.setColumns(20);
        cont.setRows(5);
        cont.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cont.setMaximumSize(new java.awt.Dimension(500, 500));
        jScrollPane1.setViewportView(cont);

        javax.swing.GroupLayout initialLayout = new javax.swing.GroupLayout(initial);
        initial.setLayout(initialLayout);
        initialLayout.setHorizontalGroup(
            initialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(initialLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(initialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ide, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                    .addGroup(initialLayout.createSequentialGroup()
                        .addComponent(categories, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(choose, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addGap(44, 44, 44))
        );
        initialLayout.setVerticalGroup(
            initialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(initialLayout.createSequentialGroup()
                .addComponent(ide, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(initialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(choose, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                    .addComponent(categories, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(204, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(initial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(initial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initialKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_initialKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_initialKeyReleased

    private void initialKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_initialKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_initialKeyPressed

    private void initialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_initialKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_initialKeyTyped

    private void initialMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_initialMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_initialMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new window().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel categories;
    private javax.swing.JLabel choose;
    private javax.swing.JTextArea cont;
    private javax.swing.JLabel ide;
    private javax.swing.JPanel initial;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
